# Available languages: en_US, fr_FR
# The database section is where the statistics of the users will be saved
# Compatible with: SQLITE (default) and MYSQL
# Port 3306 is MySQL's default.
version: ${project.version}
lang: en_US
database:
  type: SQLite
  host: localhost
  port: 3306
  user: ''
  password: ''
  database: ''
  prefix: dac_
  use_SSL: false