name: DAC
version: ${project.version}
main: sr.dac.main.Main
api-version: 1.13
authors: [clipsy1]
description: The true Dé à Coudre plugin ! Lets have fun !
website: skyrepublic.fr
commands:
  dac:
    description: main plugin command
    usage: /dac
permissions:
  dac.reload:
    description: Reload dac plugin
    default: op