name: DAC
version: ${project.version}
main: sr.dac.main.Main
api-version: 1.13
authors: [clipsy1]
description: The true Dé à Coudre plugin ! Lets have fun !
website: skyrepublic.fr
commands:
  dac:
    description: main plugin command
    usage: /dac
permissions:
  dac.*:
    description: Give all permissions for the plugin
    default: op
    children:
      dac.basics: true
      dac.admin: true
  dac.basics:
    description: All the permissions for your player
    default: true
    children:
      dac.join: true
      dac.leave: true
      dac.list: true
  dac.admin:
    description: All the admin permissions
    default: op
    children:
      dac.create: true
      dac.remove: true
      dac.event: true
      dac.reload: true
      dac.version: true